language: node_js
node_js:
  - node
script:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./travis/run_on_pull_requests; fi'
  - npm run build
cache:
  yarn: true
  directories:
    - node_modules
deploy:
  provider: s3
  access_key_id: $access_key_id
  secret_access_key: $secret_access_key
  bucket: rahulrana
  acl: public_read
  skip_cleanup: true
  local_dir: build

branches:
  only:
    - master
