language: node_js
node_js:
  - node
cache:
  yarn: true
  directories:
    - node_modules
deploy:
  provider: s3
  access_key_id: $access_key_id
  secret_access_key: $secret_access_key
  bucket: rahulrana
  acl: public_read
  skip_cleanup: true
